### ISSUE TITLE
Support non namespaced input

### ISSUE THREAD

**Issue by MoOx** [RnbWd/postcss-component#1]
What if you also support non namespaced output too ?

Input

``` css
  .App-main {
    width: 100%;
    height: 100%;
  }
  .App-button {
    background: blue;
  }
```

``` js
{
    "App-main": { width: '100%', height: '100%' },
    "App-button": { background: 'blue' }
  }
```

I might be interested by this plugin but I just use namespaced class already (bem) and each react component have already it's own file.

It's just an idea :)
